services:
  db:
    container_name: cinema-db-dev
    image: postgres:18-alpine
    restart: always
    volumes:
      - db_data_dev:/var/lib/postgresql
      - ./apps/api/dbSchema.sql:/docker-entrypoint-initdb.d/dbSchema.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_DATABASE:-database}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-root} -d ${DB_DATABASE:-database}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data_dev:
    driver: local
